resource "vault_auth_backend" "approle" {
  type        = "approle"
  path        = var.path
  description = "AppRole managed by Terraform"
}

resource "vault_approle_auth_backend_role" "role" {
  depends_on = [vault_auth_backend.approle]
  backend        = var.path
  role_name      = var.role_name
  token_policies = var.policies
}

resource "vault_approle_auth_backend_role_secret_id" "id" {
  depends_on = [vault_approle_auth_backend_role.role]
  backend   = var.path
  role_name = var.role_name
  metadata  = <<EOT
{
  "source": "Generated by Terraform Vault Provider"
}
EOT
}

resource "vault_approle_auth_backend_login" "login" {
  depends_on = [vault_approle_auth_backend_role.role,vault_approle_auth_backend_role_secret_id.id]
  backend    = var.path
  role_id    = vault_approle_auth_backend_role.role.role_id
  secret_id  = vault_approle_auth_backend_role_secret_id.id.secret_id
}

resource vault_identity_entity_alias "alias" {
  depends_on = [vault_auth_backend.approle,vault_identity_entity.entity]
  name           = var.role_name
  mount_accessor = vault_auth_backend.approle.accessor
  canonical_id   = vault_identity_entity.entity.id
}

resource vault_identity_entity "entity" {
  name = var.role_name
}
